version: '3'
services: 
  basebot:
    build: basebot/
    image: basebot:latest
  grcanosabot:
    build: grcanosabot/
    restart: always
    depends_on:
      - basebot
    network_mode: host
    container_name: grcanosabot
    volumes:
      - "./grcanosabot/src/grcanosabot/:/code/grcanosabot"
  # renfebot:
  #   build: renfebot/
  #   restart: always
  #   depends_on:
  #     - basebot
  #   container_name: renfebot
  #   network_mode: host
  #   volumes:
  #     - "./renfebot/shared/:/mnt/shared/"